import {Product, ProductCategory} from "../../components/products/types/types";

export const products: Product[] = [
    {
        id: 1,
        name: "Cinnamon Spice",
        description: "Warm and inviting, this candle is made with natural cinnamon oil to create a cozy and comforting atmosphere.",
        price: 25.99,
        category: ProductCategory.HOME,
    },
    {
        id: 2,
        name: "Ocean Breeze",
        description: "Bring the freshness of the ocean into your home with this refreshing candle. Made with natural sea salt and essential oils.",
        price: 19.99,
        category: ProductCategory.HOME,
    },
    {
        id: 3,
        name: "Lavender Fields",
        description: "Relax and unwind with this calming candle. Made with natural lavender oil to promote tranquility and relaxation.",
        price: 22.99,
        category: ProductCategory.HOME,
    },
    {
        id: 4,
        name: "Citrus Burst",
        description: "Revitalize your senses with this zesty and refreshing candle. Made with natural citrus oils to awaken and energize.",
        price: 18.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 5,
        name: "Vanilla Bean",
        description: "Indulge in the sweet and creamy aroma of vanilla with this luxurious candle. Made with natural vanilla extract to create a warm and comforting atmosphere.",
        price: 27.99,
        category: ProductCategory.HOME,
    },
    {
        id: 6,
        name: "Coconut Paradise",
        description: "Escape to a tropical paradise with this exotic candle. Made with natural coconut oil to transport you to a sun-kissed beach.",
        price: 21.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 7,
        name: "Rose Garden",
        description: "Step into a blooming garden with this romantic candle. Made with natural rose oil to create a delicate and floral ambiance.",
        price: 24.99,
        category: ProductCategory.HOME,
    },
    {
        id: 8,
        name: "Spiced Apple",
        description: "Experience the cozy and comforting aroma of spiced apple with this delicious candle. Made with natural apple and cinnamon oils to evoke a sense of warmth and nostalgia.",
        price: 26.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 9,
        name: "Eucalyptus Forest",
        description: "Breathe in the fresh and invigorating scent of eucalyptus with this revitalizing candle. Made with natural eucalyptus oil to clear your mind and refresh your senses.",
        price: 23.99,
        category: ProductCategory.HOME,
    },
    {
        id: 10,
        name: "Minty Mojito",
        description: "Get ready to party with this refreshing and invigorating candle. Made with natural mint oil to create a cool and revitalizing atmosphere.",
        price: 20.99,
        category: ProductCategory.HOME,
    },
    {
        id: 11,
        name: "Holiday Cheer",
        description: "Get into the holiday spirit with this festive and cheerful candle. Made with natural pine and cinnamon oils to create a cozy and joyful ambiance.",
        price: 29.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 12,
        name: "Citrus Burst",
        description: "Revitalize your senses with this zesty and refreshing candle. Made with natural citrus oils to awaken and energize.",
        price: 18.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 13,
        name: "Vanilla Bean",
        description: "Indulge in the sweet and creamy aroma of vanilla with this luxurious candle. Made with natural vanilla extract to create a warm and comforting atmosphere.",
        price: 27.99,
        category: ProductCategory.HOME,
    },
    {
        id: 14,
        name: "Coconut Paradise",
        description: "Escape to a tropical paradise with this exotic candle. Made with natural coconut oil to transport you to a sun-kissed beach.",
        price: 21.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 15,
        name: "Rose Garden",
        description: "Step into a blooming garden with this romantic candle. Made with natural rose oil to create a delicate and floral ambiance.",
        price: 24.99,
        category: ProductCategory.HOME,
    },
    {
        id: 16,
        name: "Spiced Apple",
        description: "Experience the cozy and comforting aroma of spiced apple with this delicious candle. Made with natural apple and cinnamon oils to evoke a sense of warmth and nostalgia.",
        price: 26.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 17,
        name: "Eucalyptus Forest",
        description: "Breathe in the fresh and invigorating scent of eucalyptus with this revitalizing candle. Made with natural eucalyptus oil to clear your mind and refresh your senses.",
        price: 23.99,
        category: ProductCategory.HOME,
    },
    {
        id: 18,
        name: "Minty Mojito",
        description: "Get ready to party with this refreshing and invigorating candle. Made with natural mint oil to create a cool and revitalizing atmosphere.",
        price: 20.99,
        category: ProductCategory.HOME,
    },
    {
        id: 19,
        name: "Holiday Cheer",
        description: "Get into the holiday spirit with this festive and cheerful candle. Made with natural pine and cinnamon oils to create a cozy and joyful ambiance.",
        price: 29.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 20,
        name: "Lavender Fields",
        description: "Relax and unwind with this calming candle. Made with natural lavender oil to promote tranquility and relaxation.",
        price: 22.99,
        category: ProductCategory.HOME,
    },
    {
        id: 21,
        name: "Citrus Burst",
        description: "Revitalize your senses with this zesty and refreshing candle. Made with natural citrus oils to awaken and energize.",
        price: 18.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 22,
        name: "Vanilla Bean",
        description: "Indulge in the sweet and creamy aroma of vanilla with this luxurious candle. Made with natural vanilla extract to create a warm and comforting atmosphere.",
        price: 27.99,
        category: ProductCategory.HOME,
    },
    {
        id: 23,
        name: "Coconut Paradise",
        description: "Escape to a tropical paradise with this exotic candle. Made with natural coconut oil to transport you to a sun-kissed beach.",
        price: 21.99,
        category: ProductCategory.GARDEN,
    },
    {
        id: 24,
        name: "Vanilla Bean",
        description: "Indulge in the sweet and creamy aroma of vanilla with this luxurious candle. Made with natural vanilla extract to create a warm and comforting atmosphere.",
        price: 27.99,
        category: ProductCategory.HOME,
    },
]